name: 'Heyhack Start Penetratition Test Action'
author: 'Heyhack'
description: 'GitHub Action to automatically start a penetration test in Heyhack.'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  profileId:
    description: 'The ID of the profile you wish to use for the penetration test (find this ID in your Heyhack account).'
    required: true
  apiKey:
    description: 'The API key required to authenticate with your Heyhack account.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.profileId }}
    - ${{ inputs.apiKey }}